### ISSUE TITLE
Exception when native runtime assembly reference doesn't exist

### ISSUE THREAD

**Issue by lukevp** [extism/dotnet-sdk#78]
The SDK should verify at startup in managed code whether the Extism runtime is installed, because it doesn't really make sense to use the SDK without Extism.  

1. currently, if the `Extism.runtime.all` is not installed, dotnet just crashes with a 139 exit code.  It's an untrappable exception with `try/catch`, I'm assuming because it is happening in unmanaged code somewhere. 
2. `Extism.runtime.all` seems to be needed in the calling code and not in a shared library.  I'm building a `.dll` that can execute an Extism function, so it has the Extism SDK installed, but I have to install the `Extism.runtime.all` in the app that includes the library. This makes sense to me, but it means that the SDK => Extism link can't happen within Nuget as package dependencies, since they're installed at 2 different levels.
3. The SDK should probably have some type of versioning range on which Extisms it can support - eg. should SDK 0.2 be able to be installed alongside Extism 1.1? probably not, because the API surface likely has changed, and since this is all unmanaged code, it'll probably fail in weird ways at runtime if the .net library tries to bind to a native library that exposes a different API surface.

**Comment by mhmd-azeez** [comment]
Hi, that's a good question

> it's an untrappable exception with try/catch

If the native library is not found, it throws a `DllNotFoundException`. You can catch it like so:
```csharp
var manifest = new Manifest(new UrlWasmSource("https://github.com/extism/plugins/releases/latest/download/count_vowels_kvstore.wasm"));

try
{
    var hf = HostFunction.FromMethod("kv_read", IntPtr.Zero, (CurrentPlugin plugin, long keyOffset) =>
    {
        var key = plugin.ReadString(keyOffset);
        if (!kvStore.TryGetValue(key, out var value))
        {
            value = [0, 0, 0, 0];
        }

        return plugin.WriteBytes(value);
    });

    using var plugin = new Plugin(manifest, [hf], withWasi: true);
    var output = Encoding.UTF8.GetString(
        plugin.Call("count_vowels", Encoding.UTF8.GetBytes("Hello World!"))
    );

    Console.WriteLine($"Output: {output}");
}
catch (DllNotFoundException ex)
{
    Console.WriteLine(ex.Message);
}

Console.WriteLine("Done");
```

Output:
```
Unable to load DLL 'extism' or one of its dependencies: The specified module could not be found. (0x8007007E)
Done
```
Notice how "Done" is also printed.

> Extism.runtime.all seems to be needed in the calling code and not in a shared library

Yes, only the main app needs to reference the native library nuget package

> but it means that the SDK => Extism link can't happen within Nuget as package dependencies, since they're installed at 2 different levels.

Yeah, tbh not sure if there is a good way around that. I don't want to put a hard dependency from Extism.Sdk to Extism.runtime.all because people might only be interested in one runtime (e.g. they might only need to run on linux-x64), adding all of the runtimes bloats the app size quite a bit. Suggestions are welcome though

> The SDK should probably have some type of versioning range on which Extisms it can support 

@bhelx has done some research on a versioning scheme in the past:
https://github.com/extism/proposals/blob/main/EIP-005-extism-versioning-system.md

Currently, I am planning on keeping .NET SDK's major version in sync with the native library's major version. But for minor versions won't match. But you should always be able to use the latest version of the SDK with the latest version of the native library.

**Comment by bhelx** [comment]
I think the comments answer the questions, but feel free to re-open for follow up discussion @lukevp !
